-- Load tokens from database with rotation every N requests
local tokens = {}
local token_index = 1
local request_counter = 0
local ROTATE_EVERY = 10  -- Change token every 10 requests

local gateway_secret = os.getenv("GATEWAY_SECRET") or "test-secret"
local alg = os.getenv("JWT_ALGORITHM") or "RS256"

-- Load tokens from file (generated by Rust script)
function load_tokens_from_file(filename)
    local file = io.open(filename, "r")
    if not file then
        print("Error: Cannot open " .. filename)
        return {}
    end

    local result = {}
    for line in file:lines() do
        local token = line:gsub("%s+", "")
        if token ~= "" then
            table.insert(result, token)
        end
    end
    file:close()
    return result
end

function init(args)
    -- Load tokens from file
    local filename = "wrk/tokens_" .. alg .. ".txt"
    tokens = load_tokens_from_file(filename)
    print("Loaded " .. #tokens .. " tokens from " .. filename)

    if #tokens == 0 then
        print("WARNING: No tokens loaded! Using fallback.")
        for i = 1, 100 do
            tokens[i] = "test-token-" .. i
        end
    end

    token_index = 1
    request_counter = 0
end

function request()
    -- Rotate token every ROTATE_EVERY requests
    request_counter = request_counter + 1
    if request_counter % ROTATE_EVERY == 0 then
        token_index = token_index + 1
        if token_index > #tokens then
            token_index = 1
        end
    end

    local token = tokens[token_index]

    local body = '{"token":"' .. token .. '"}'
    local headers = {
        ["X-Gateway-Secret"] = gateway_secret,
        ["Content-Type"] = "application/json"
    }

    return wrk.format("POST", nil, headers, body)
end
